.travis.yml

Deploy Documentation with Travis

---

.travis.yml

Add python 3.8 to ci

---

tests/test_channel.py
tests/virtuoso.py

Make test not take ages

---

skillbridge/server/python_server.il

Strip whitespace from loaded path name in Skill script

---

skillbridge/client/objects.py

Expose skill id for remote objects

---

docs/usage/server.rst
skillbridge/server/python_server.il

```lisp
pyStartServer ?python "python3.6"
```

Make python path configurable

---

.gitignore
skillbridge/__init__.py
skillbridge/client/workspace.py
tests/test_channel.py

```python
from skillbridge import Workspace, current_workspace
ws = Workspace.open().make_current()
cv = current_workspace.ge.get_edit_cell_view()
```

Make workspaces available globally

---

skillbridge/client/extract.py

Typo in user warning

---

.gitignore
skillbridge/__main__.py
skillbridge/client/channel.py
skillbridge/client/workspace.py
skillbridge/server/python_server.il
skillbridge/server/python_server.py
tests/test_channel.py
tests/test_server.py
tests/virtuoso.py

Add windows tcp channel

---

skillbridge/test/__init__.py
skillbridge/test/channel.py
tests/test_test_channel.py

Add dummy channel for offline tests

---

skillbridge/__main__.py

No absolute path for definitions import/export required

---

skillbridge/__main__.py

Add --force option to import command

---

skillbridge/client/objects.py

Remoteobject maxsplit

---

docs/usage/quickstart.rst
skillbridge/client/channel.py
skillbridge/client/workspace.py
tests/test_misc.py

Implement direct mode

---

skillbridge/client/channel.py
skillbridge/server/python_server.il
tests/test_misc.py

`DirectChannel` also needed some adjustments. Looks like `input()` is better at getting input from stdin than `sys.stdin.readline()`.

Add pyRun to start direct mode scripts

---

skillbridge/client/objects.py
tests/test_channel.py

Implement better inspection for RemoteObject

---

docs/examples/basic.rst
skillbridge/__init__.py
skillbridge/client/functions.py
skillbridge/client/hints.py
tests/test_channel.py
tests/test_misc.py
tests/test_translator.py
tests/virtuoso.py

Add `Key` class and `keys` utility function to call nested key parameters in SKILL

---

.coveragerc
.gitattributes

Remove obsolete files

---

skillbridge/server/python_server.il

Add missing type annotation

---

docs/examples/custom_functions.rst
skillbridge/client/functions.py
skillbridge/client/workspace.py
tests/test_misc.py

Added __get_item__ to Workspace for direct functions

---

skillbridge/__init__.py

Use staticmethod for SKILL function stubs

---

skillbridge/server/python_server.il

Fix warning behaviour for the allegro skill interpreter

---

skillbridge/client/objects.py
skillbridge/client/translator.py
skillbridge/server/python_server.py

Ignore missing objType when printing objects

---

docs/examples/create_path.rst

This fixes an error in the "Create some paths" example. Also it removes some unnecessary code.
Closes #143

Fix error in example

---

docs/examples/funcall.rst
skillbridge/client/objects.py
tests/test_channel.py
tests/test_translator.py

Implement funcall shortcut

---

skillbridge/client/translator.py
tests/test_translator.py

Fixed camel_to_snake

---

skillbridge/client/objects.py
skillbridge/server/python_server.il
tests/test_channel.py

Correctly serialize and deserialize port objects

---

docs/examples/globals.rst
docs/usage/quickstart.rst
skillbridge/client/channel.py
skillbridge/server/python_server.py

Add direct mode docs

---

skillbridge/client/objects.py
tests/test_misc.py

Handle double hex prefixes in remote object names

---

docs/examples/basic.rst
tests/test_translator.py

Add a short paragraph describing how to use quoted symbols

Document quoted symbols

---

.gitignore
docs/examples/tables_vectors.rst
setup.cfg
skillbridge/__init__.py
skillbridge/__main__.py
skillbridge/client/channel.py
skillbridge/client/hints.py
skillbridge/client/objects.py
skillbridge/client/remote.py
skillbridge/client/translator.py
skillbridge/client/workspace.py
skillbridge/server/python_server.il
tests/test_channel.py
tests/test_integration.py
tests/test_misc.py
tests/test_test_channel.py
tests/test_translator.py
update_version.py

Closes #190 
Example:
```python
ws = Workspace.open()
table = ws.make_table('MyTable', default=None)
print(table['x'])
table['x'] = 1
del table['x']
```
The `RemoteTable` basically behaves like a python `dict`

Add support for tables and vectors

---

skillbridge/client/channel.py
skillbridge/client/workspace.py
tests/test_workspace.py

Don't fail on workspace close when channel close fails

---

.github/workflows/pythonpackage.yml
skillbridge/client/objects.py
tests/test_misc.py

Add fast remote object repr

---

skillbridge/server/python_server.il
tests/test_integration.py

203 nil t nil is not a dict

---

skillbridge/client/workspace.py

196 deprecate

---

.github/workflows/release.yml
setup.cfg
skillbridge/client/translator.py
skillbridge/client/workspace.py
skillbridge/version.py
tests/test_channel.py
tests/test_integration.py
tests/test_test_channel.py
update_version.py

- Pull version number from single source
- Commit version number after build

Streamline build process

---

skillbridge/__init__.py

Makes sure that the generated `workspace.pyi` lands in the correct place
Closes #230

Repair static completion after mypy behavior change

---

update_version.py

Checkout master before reading hash

Final final fix of version bump

---

update_version.py

Fetch before checkout
